esphome:
  name: esp32-adc-calibration

esp32:
  variant: esp32
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  adc_calibration:
    url: https://github.com/Youpimatin/esphome-esp32-adc-calibrate
    files:
      - path: package.yaml
    ref: main
    refresh: 1d


interval:
  - interval: 1s
    then:
      - lambda: |-
          float value = id(adc_calibrator).read();

          if (!isnan(value)) {
            ESP_LOGI(
              "main",
              "ADC linéarisé = %.2f",
              value
            );
          }
